### ISSUE TITLE
Failed to add foreign key constraint

### ISSUE THREAD

**Issue by iamleson98** [mattermost/morph#14]
Hello!

I created files like below:

```sql
-- 001_create_car.up.sql

CREATE TABLE car (
     id bigint auto increment primary key,
     manufacturer_id bigint
);

ALTER TABLE car ADD CONSTRAINT fk_car_manufacturer 
     FOREIGN KEY (manufacturer_id) REFERENCES manufacturer(id);


-- 002_create_manufacturer.up.sql

CREATE TABLE manufacturer (
    id bigint auto increment primary key,
    name varchar(100)
);
```

As you can see, Morph will migrate file `001_create_car.up.sql` first, then `002_create_manufacturer.up.sql`.

But I got the error says `relation "manufacturer" does not exist`.

So could anybody tell me how to fix this ? Do I need to create another `003....up.sql` file and define `CONSTRAINT` in it ?

Thank you, mr @isacikgoz  :1st_place_medal:

**Comment by isacikgoz** [comment]
Hey @iamleson98 thanks for having interest in using morph!! Now when I check the script you shared, you need to create `manufacturer` table first to be able to add the foreign key constraint. You can either create `manufacturer` table first then `car` table, or, move `ALTER TABLE car ADD CONSTRAINT fk_car_manufacturer ...` to a 3rd script file.

**Comment by iamleson98** [comment]
Thank you for your response, mr @isacikgoz !

As you suggested, I decided to create new files for foreign key constraints. It works smoothly thank to you.
